#!/bin/bash

echo "=================================="
echo "🚀 Gmail AI Manager - Quick Start"
echo "=================================="
echo ""
echo "✅ All issues have been fixed!"
echo ""
echo "📊 Current Status:"
echo "  - Backend: Running on http://localhost:8003"
echo "  - Frontend: Running on http://localhost:3000"
echo "  - Database: 88 emails loaded"
echo "  - Account: deshpande.raghavendra@gmail.com"
echo ""
echo "🎯 Quick Access URLs:"
echo ""
echo "  1. Home Page:"
echo "     http://localhost:3000"
echo ""
echo "  2. Dev Login (Auto-authenticate):"
echo "     http://localhost:3000/dev-login"
echo ""
echo "  3. Dashboard (View emails):"
echo "     http://localhost:3000/dashboard"
echo ""
echo "  4. Backend API Docs:"
echo "     http://localhost:8003/docs"
echo ""
echo "=================================="
echo "🎉 How to Test Right Now:"
echo "=================================="
echo ""
echo "Option 1: One-Click Dev Login"
echo "  1. Open: http://localhost:3000"
echo "  2. Click 'Dev Login' button"
echo "  3. Automatically redirected to dashboard with emails!"
echo ""
echo "Option 2: Direct Dashboard Access"
echo "  1. Open: http://localhost:3000/dev-login"
echo "  2. Wait 2 seconds for auto-login"
echo "  3. View your 88 emails!"
echo ""
echo "=================================="
echo "📝 What Was Fixed:"
echo "=================================="
echo ""
echo "  ✅ OAuth redirect URI (port 8003)"
echo "  ✅ Development token generation endpoint"
echo "  ✅ Auto-login page for testing"
echo "  ✅ Frontend navigation improvements"
echo "  ✅ Error messages and documentation"
echo ""
echo "=================================="
echo "⚠️  For Production OAuth:"
echo "=================================="
echo ""
echo "Currently using placeholder OAuth credentials."
echo "To enable real Google OAuth:"
echo ""
echo "  1. Get credentials from Google Cloud Console"
echo "  2. Update .env file (lines 9-10):"
echo "     GMAIL_CLIENT_ID=your_real_id"
echo "     GMAIL_CLIENT_SECRET=your_real_secret"
echo "  3. Restart backend: docker restart gmail-ai-backend"
echo ""
echo "=================================="
echo "🔧 Useful Commands:"
echo "=================================="
echo ""
echo "  # Check backend logs"
echo "  docker logs -f gmail-ai-backend"
echo ""
echo "  # Restart backend"
echo "  docker restart gmail-ai-backend"
echo ""
echo "  # View database"
echo "  docker exec -it gmail-ai-postgres psql -U gmail_user -d gmail_ai"
echo ""
echo "  # Generate new dev token"
echo "  curl http://localhost:8003/api/v1/auth/dev/token/1 | jq"
echo ""
echo "=================================="
echo "📚 Documentation:"
echo "=================================="
echo ""
echo "  See ISSUES_FIXED.md for complete details"
echo ""
